CREATE TABLE PLAN ( PLAN_ID INT(100) AUTO_INCREMENT PRIMARY KEY, TASK_NAME VARCHAR(100) NOT NULL,
 ASSESMENT VARCHAR(1000), USEFUL_LINK VARCHAR(1000) );


CREATE TABLE ASSOCIATE ( 
	ASSOCIATE_ID INT(100) AUTO_INCREMENT PRIMARY KEY, 
    ASSOCIATE_NAME VARCHAR (100) NOT NULL,
    EMAIL_ADDRESS VARCHAR (500) NOT NULL,
    PASSWORD VARCHAR (20) NOT NULL
     );
    
CREATE TABLE MENTOR (
	MENTOR_ID INT(100) auto_increment PRIMARY KEY,
    MENTOR_NAME VARCHAR (100) NOT NULL,
    PASSWORD VARCHAR (50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    ORGANIZATION VARCHAR (100),
    ROLE VARCHAR (50) NOT NULL,
    AREA_OF_INTEREST VARCHAR (100),
    EXPERTIES VARCHAR (100),
    PHOTO LONGBLOB );


CREATE TABLE ADMINS (
	ADMIN_ID INT(100) AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR (100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR (100) NOT NULL,
    MENTOR_ID INT(100) REFERENCES MENTOR (MENTOR_ID),
    ASSOCIATE_ID INT(100) REFERENCES ASSOCIATE(ASSOCIATE_ID)
    );
    
-- ASSOCIATION
CREATE TABLE PLAN_ASSOCIATE (
	PLAN_ASSOCIATE_ID INT(100) auto_increment PRIMARY KEY,
    PLAN_ID INT(100) references PLAN(PLAN_ID),
    ASSOCIATE_ID INT(100) references ASSOCIATE(ASSOCIATE_ID),
    ASSIGN_DATE DATE, UPDATED_DATE DATE, PERCENT_COMPLETE DECIMAL(5,2)
    );

CREATE TABLE PLAN_MENTOR_ASSOCIATE (
	PLAN_MENTOR_ID INT(100) AUTO_INCREMENT PRIMARY KEY,
    PLAN_ASSOCIATE_ID INT(100) references PLAN_ASSOCIATE(PLAN_ASSOCIATE_ID),
    MENTOR_ID INT(100) REFERENCES MENTOR (MENTOR_ID) );
    
    
    
    
DROP TABLE PLAN_MENTOR;
    
    
    
    
    
    