CREATE VIEW PLAN_MENTOR_ASSOCIATE_VIEW AS 
SELECT 
    PMa.PLAN_MENTOR_ASSOCIATE_ID,
    M.MENTOR_ID,
    M.MENTOR_NAME,
    M.EMAIL,
    M.ORGANIZATION,
    M.ROLE,
    M.AREA_OF_INTEREST,
    M.EXPERTIES,
    M.PHOTO,
    PA.PLAN_ASSOCIATE_ID,
    PA.PLAN_ID,
    P.TASK_NAME,
    P.ASSESMENT,
    A.ASSOCIATE_NAME,
    A.EMAIL_ADDRESS,
    PA.ASSIGN_DATE,
    PA.UPDATED_DATE,
    PA.PERCENT_COMPLETE
FROM
	PLAN_MENTOR_ASSOCIATE PMA
	INNER JOIN 	MENTOR M ON PMA.MENTOR_ID = M.MENTOR_ID
	INNER JOIN  PLAN_ASSOCIATE PA ON PMA.PLAN_ASSOCIATE_ID = PA.PLAN_ASSOCIATE_ID
	INNER JOIN  ASSOCIATE A ON PA.ASSOCIATE_ID = A.ASSOCIATE_ID
	INNER JOIN  PLAN P ON PA.PLAN_ID = P.PLAN_ID;
    

CREATE VIEW PLAN_ASSOCIATE_VIEW AS
SELECT 
    PA.PLAN_ASSOCIATE_ID,
    PA.PLAN_ID,
    P.TASK_NAME,
    P.ASSESMENT,
    A.ASSOCIATE_NAME,
    A.EMAIL_ADDRESS,
    PA.ASSIGN_DATE,
    PA.UPDATED_DATE,
    PA.PERCENT_COMPLETE
FROM
    PLAN_ASSOCIATE PA
        INNER JOIN
    ASSOCIATE A ON PA.ASSOCIATE_ID = A.ASSOCIATE_ID
        INNER JOIN
    PLAN P ON PA.PLAN_ID = P.PLAN_ID
;

SELECT * FROM PLAN_ASSOCIATE_VIEW;